development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ecommerceonrails_development
  pool:     5
  username: ecommerceonrails_app
  password: rails
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: ecommerceonrails_test
  pool:     5
  username: ecommerceonrails_app
  password: rails
  template: template0